name: PR test

on:
 push

jobs:
  RunTest:
    name: Run Jest
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout repo
        uses: actions/checkout@master
      - name: npm install
        run: yarn plugin import workspace-tools && yarn install
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.0
#       - name: merge PR if success test
#         uses: actions/github-script@0.3.0
#         with:
#           github-token: ${{github.token}}
#           script: |
#             github.pulls.merge({
#               ...context.repo
#             })
#           if: success()
      - name: GitHub Script create issue
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
              github.issues.create({
              ...context.repo,
              title: 'Failed merge PR',
              body: '테스트가 실패하였습니다. '
              })
          if: failure()
#       - name: automerge
#         uses: "pascalgn/automerge-action@733fcc62d711705eae9cd66fcf49c93c1d1a98c6"
#         env:
#           GITHUB_TOKEN: "${{ secrets.TOKEN }}"
#           MERGE_LABELS: "automerge"
#           MERGE_COMMIT_MESSAGE: "automatic"
