name: TEST CUSTOM ACTIONS
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: plm9606/automerge_actions@master
      with:
        who-to-greet: 'JS actions'
