on: push

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: plm9606/github-action@master
      with:
        who-to-greet: 'Mona the Octocat'
        args: '{\"channel\":\"GQ6BU15EJ\",\"text\":\"성공 \"}'
