
name: service test11111
on: 
  push:
    branches: 
      - service
      - test
jobs:
  test:
    name: service branch test1111
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: test root
        run: |
          npm install
          npm test
      - name: test gateway
        run: |
          
          echo 1. ${{github.ref}}
          echo 2. ${GITHUB_REF#refs/heads/}
          if [ ${{github.ref}} == "log" ];
          then
            cd ./src/gateway
            npm install
            npm test
#       - name: get branch name
#         run: echo running on branch ${GITHUB_REF##*/}
#         with:
#           ref: ${{ github.ref }}
