
name: service test11111
on: 
  push:
    branches: 
      - service
      - test
jobs:
  test:
    name: service branch test1111
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: test root
        run: |
          set root_dir=%cd%
          myvar="$PWD"
          echo root path is $myvar
          npm install
          npm test
      - name: test gateway
        run: |
          echo %root_dir%
          echo current branch is ${GITHUB_REF#refs/heads/} , $myvar
          if [  ${GITHUB_REF#refs/heads/} == "service" ];
          then
            cd ./src/gateway
            npm install
            npm test
          fi
#       - name: get branch name
#         run: echo running on branch ${GITHUB_REF##*/}
#         with:
#           ref: ${{ github.ref }}
