
name: service test11111
on: 
  push:
    branches: 
      - service
      - test
jobs:
  test:
    name: service branch test1111
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@master
