name: webhook
on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: 16team
        SLACK_USERNAME: mergeBot
        SLACK_COLOR: good
        SLACK_TITLE: Message
        SLACK_MESSAGE: '한글 테스트'
