name: PR test

on: 
  pull_request_review_comment:
    types: [created, edited, deleted]
    branches: 
      - master
      - develop

jobs:
  RunTest:
    name: Run Jest
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout repo
        uses: actions/checkout@master
      - name: npm install
        run: npm install
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.0
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKENS }}
          number: 1
        if: success()
