name: PR test

on:
  push:
    branches: 
      - master
      - develop
      - test
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches: 
      - master
      - develop

jobs:
  RunTest:
    name: Run Jest
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout repo
        uses: actions/checkout@master
      - name: npm install
        run: npm install
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.0
      - name: merge PR
        uses: "pascalgn/automerge-action@733fcc62d711705eae9cd66fcf49c93c1d1a98c6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKENS }}"
