name: service test
on:
  push:
    branches:
      - service
jobs:
  Servicetest:
    name: Test gateway
    runs-on: ubuntu-latest
    steps:
      - name: test root
        run: |
          npm install
          npm test
      - name: test gateway
        run: |
          cd ./src/gateway
          npm install
          npm test
