name: service PR Test

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - test

jobs:
  RunTest:
    name: service PR Test
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout repo
        uses: actions/checkout@master
      - name: run service test
        run: |
          echo sha is ${{github.sha}}
          echo base_ref is ${{github.base_ref}}
          echo head_ref is ${{github.head_ref}}
          echo ref is " ${{github.ref}} "
            npm install
            npm test
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            const refss = "${{github.ref}}"
            console.log(typeof refss)
            const pr_number = Number(refss.split("/")[2])
            const reviews = await github.pulls.listReviews({
              ...context.repo,
              pull_number: pr_number
            })
            console.log(reviews.data.length)
            if(reviews.data.length <= 3) throw('err')
            else return true
